### ISSUE TITLE
Manage DESTDIR during installatio

### ISSUE THREAD

**Issue by ycollet** [fps/fps-plugins.lv2#3]
For packaging most of the install phase support the DESTDIR parameter.

**Comment by fps** [comment]
Hi, there's an INSTALL_DIR variable which you can set with e.g. 

`INSTALL_DIR=/path/to/dir make install`

Is that not good enough?

**Comment by fps** [comment]
I read the docs on DESTDIR. I added support here: https://github.com/fps/fps-plugins.lv2/commit/5aa981a2c6b87ac3f7599ee99f3a53832de3afa6

**Comment by ycollet** [comment]
Excellent, thanks a lot !
